user_token: YTkyMmNiNTktN2ZjNS00ZTRmLWI2MTMtOGRhOGNiMTU4ODVkXzc1ODE=

session:
  key: key_to_generate
admin:
  email: admin@admin.com
  password: admin
bot:
  token: vk1.a.UXtr-eondruIUMpZr0AkKuZmg5_oSsiytZCye3bxchQU4v39L5WbVFHJWxsMcfru3DfXdPtPVDrJp4fe49eEaZwgTwMb0c8aNahTLHeOO1ScBxVplpoIqLpFf6yvcVXcUBHkSoolDN19f8mIX0a6UDB_GxGVPg8z3XNRTE7t1p7_K4xe5TYezlCSVtvLyuKRxlxeE_GwbNa-B3gqltw5-w
  group_id: 236013203


